from . import help
from . import start
from . import admin
from . import ish_joy
from . import full_name_ask1
from . import age_ask1
from . import ask_techno
from . import ask_location
from . import ask_payment
from . import ask_profession
from . import ask_time
from . import ask_goal
from . import show_full_info
from . import if_true1
from . import if_false
from . import ustoz_kk
from . import full_name_ask2
from . import ask_tech2
from . import ask_contact2
from . import ask_location2
from . import ask_payment2
from . import ask_profession2
from . import ask_time2
from . import ask_goal2
from . import show_full_info2
from . import if_true2
from . import if_false2
